sudo: required
language: generic
services: docker
script:
- pwd
- ls
- docker run --rm --user="$(id -u):$(id -g)" -v "$PWD":"/repo" -w "/repo" dockershelf/latex:full
  /bin/sh -c "pwd;ls;latexmk -xelatex -interaction=nonstopmode test.tex;ls"
- ls
deploy:
  provider: releases
  api_key:
    secure: dHhBwk4lQXtA4XgUhz6fefzX5hPs2TGaTRtt0npGwlpESz0nQf2UQVJoDzlhzOplXCdsV2EDlPEnwFm5x4kTrwtETwbeK/UArIh6fmo7hGPeyWwPCFNnHX422Vi6nh4DDuWUk/ObCGUN9TZMpFglQag826aI9pEU6k89KcpS3EilIgUYggHUz5EOj59qtV37Fgr7s6hT4NBJaFuLDjJV4PYjTqeEAffJ+gjgVub5cOQT4NSgQW1fEmYS5OZoOMS2mKxz6LYBg76Ys8H4el7QuKy7QodAgkGLsxBTib83eMrpE4P7KqBLQKl3oXzAk8+XVzW4rhscMX2jFD6Sg/to1PaPviU7WQyYrgtdVkrLXzwKCUy7zQAUoIckrq4n9GICPfVpHeKcLHMu/9xKqipZwTjpFBxLTkmnbUV4dGx5cgVtrf2PsLcKJOjFGDvfnISIzPp/tfTtzL22tCRvJeMOjDULPvHKIapIuy7u85fDlhibynbERhZIGlZ88Wt73kXX2I9Hck11btBFlyRtBTqrapRNfSVK3/BGAH+js0s4bm+gdGniFRgT2jsmSpQJFggeHmuz/4mYb+Oc3KtAxnwmjZ92kp/3+4AkmHUUpskwae+J6iUeIUP5ZypuXnrMPL4b25gh1uzNIQtzRVvwcbK9bM3W+vU30WlLufCPYLgHgBI=
  file: test.pdf
  file_glob: true
  file:
    - test.pdf
  skip_cleanup: true
  on:
    repo: hadisfr/travis-test
    tags: true
